# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './points2one/frmPoints2One.ui'
#
# Created: Sun Jun 28 21:30:08 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(350, 469)
        Dialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.wInputLayer = gui.QgsMapLayerComboBox(Dialog)
        self.wInputLayer.setFilters(gui.QgsMapLayerProxyModel.PointLayer)
        self.wInputLayer.setObjectName(_fromUtf8("wInputLayer"))
        self.verticalLayout.addWidget(self.wInputLayer)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.wCreatePolygons = QtGui.QRadioButton(Dialog)
        self.wCreatePolygons.setChecked(True)
        self.wCreatePolygons.setObjectName(_fromUtf8("wCreatePolygons"))
        self.horizontalLayout_4.addWidget(self.wCreatePolygons)
        self.wCreateLines = QtGui.QRadioButton(Dialog)
        self.wCreateLines.setObjectName(_fromUtf8("wCreateLines"))
        self.horizontalLayout_4.addWidget(self.wCreateLines)
        self.wCloseLines = QtGui.QCheckBox(Dialog)
        self.wCloseLines.setEnabled(False)
        self.wCloseLines.setCheckable(True)
        self.wCloseLines.setObjectName(_fromUtf8("wCloseLines"))
        self.horizontalLayout_4.addWidget(self.wCloseLines)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.wGroup = QtGui.QCheckBox(Dialog)
        self.wGroup.setObjectName(_fromUtf8("wGroup"))
        self.verticalLayout.addWidget(self.wGroup)
        self.wGroupField = gui.QgsFieldComboBox(Dialog)
        self.wGroupField.setEnabled(False)
        self.wGroupField.setObjectName(_fromUtf8("wGroupField"))
        self.verticalLayout.addWidget(self.wGroupField)
        self.wSort1 = QtGui.QCheckBox(Dialog)
        self.wSort1.setObjectName(_fromUtf8("wSort1"))
        self.verticalLayout.addWidget(self.wSort1)
        self.wSortField1 = gui.QgsFieldComboBox(Dialog)
        self.wSortField1.setEnabled(False)
        self.wSortField1.setObjectName(_fromUtf8("wSortField1"))
        self.verticalLayout.addWidget(self.wSortField1)
        self.wSort2 = QtGui.QCheckBox(Dialog)
        self.wSort2.setEnabled(False)
        self.wSort2.setObjectName(_fromUtf8("wSort2"))
        self.verticalLayout.addWidget(self.wSort2)
        self.wSortField2 = gui.QgsFieldComboBox(Dialog)
        self.wSortField2.setEnabled(False)
        self.wSortField2.setObjectName(_fromUtf8("wSortField2"))
        self.verticalLayout.addWidget(self.wSortField2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.wOutputFileName = QtGui.QLineEdit(Dialog)
        self.wOutputFileName.setReadOnly(True)
        self.wOutputFileName.setObjectName(_fromUtf8("wOutputFileName"))
        self.horizontalLayout.addWidget(self.wOutputFileName)
        self.wBrowse = QtGui.QPushButton(Dialog)
        self.wBrowse.setObjectName(_fromUtf8("wBrowse"))
        self.horizontalLayout.addWidget(self.wBrowse)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_3 = QtGui.QLabel(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.wEncoding = QtGui.QComboBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wEncoding.sizePolicy().hasHeightForWidth())
        self.wEncoding.setSizePolicy(sizePolicy)
        self.wEncoding.setObjectName(_fromUtf8("wEncoding"))
        self.horizontalLayout_2.addWidget(self.wEncoding)
        self.wAddResult = QtGui.QCheckBox(Dialog)
        self.wAddResult.setObjectName(_fromUtf8("wAddResult"))
        self.horizontalLayout_2.addWidget(self.wAddResult)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.wProgressBar = QtGui.QProgressBar(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wProgressBar.sizePolicy().hasHeightForWidth())
        self.wProgressBar.setSizePolicy(sizePolicy)
        self.wProgressBar.setProperty("value", 0)
        self.wProgressBar.setObjectName(_fromUtf8("wProgressBar"))
        self.horizontalLayout_3.addWidget(self.wProgressBar)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout_3.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.wCreateLines, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.wCloseLines.setEnabled)
        QtCore.QObject.connect(self.wSort1, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.wSort2.setEnabled)
        QtCore.QObject.connect(self.wSort2, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.wSortField2.setEnabled)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QObject.connect(self.wGroup, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.wGroupField.setEnabled)
        QtCore.QObject.connect(self.wInputLayer, QtCore.SIGNAL(_fromUtf8("layerChanged(QgsMapLayer*)")), self.wGroupField.setLayer)
        QtCore.QObject.connect(self.wInputLayer, QtCore.SIGNAL(_fromUtf8("layerChanged(QgsMapLayer*)")), self.wSortField1.setLayer)
        QtCore.QObject.connect(self.wInputLayer, QtCore.SIGNAL(_fromUtf8("layerChanged(QgsMapLayer*)")), self.wSortField2.setLayer)
        QtCore.QObject.connect(self.wSort1, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.wSortField1.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.wInputLayer, self.wCreatePolygons)
        Dialog.setTabOrder(self.wCreatePolygons, self.wCreateLines)
        Dialog.setTabOrder(self.wCreateLines, self.wCloseLines)
        Dialog.setTabOrder(self.wCloseLines, self.wGroup)
        Dialog.setTabOrder(self.wGroup, self.wGroupField)
        Dialog.setTabOrder(self.wGroupField, self.wSort1)
        Dialog.setTabOrder(self.wSort1, self.wSortField1)
        Dialog.setTabOrder(self.wSortField1, self.wSort2)
        Dialog.setTabOrder(self.wSort2, self.wSortField2)
        Dialog.setTabOrder(self.wSortField2, self.wOutputFileName)
        Dialog.setTabOrder(self.wOutputFileName, self.wBrowse)
        Dialog.setTabOrder(self.wBrowse, self.wEncoding)
        Dialog.setTabOrder(self.wEncoding, self.wAddResult)
        Dialog.setTabOrder(self.wAddResult, self.buttonBox)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Points2One", None))
        self.label.setText(_translate("Dialog", "Input vector layer", None))
        self.wCreatePolygons.setText(_translate("Dialog", "Create polygons", None))
        self.wCreateLines.setText(_translate("Dialog", "Create lines", None))
        self.wCloseLines.setText(_translate("Dialog", "Closed", None))
        self.wGroup.setText(_translate("Dialog", "Group features by", None))
        self.wSort1.setText(_translate("Dialog", "Sort vertices by", None))
        self.wSort2.setText(_translate("Dialog", "Then by", None))
        self.label_2.setText(_translate("Dialog", "Output shapefile", None))
        self.wBrowse.setText(_translate("Dialog", "Browse", None))
        self.label_3.setText(_translate("Dialog", "Encoding", None))
        self.wAddResult.setText(_translate("Dialog", "Add result to canvas", None))

from qgis import gui
